import "node_modules/bootswatch/dist/minty/bootstrap.min.css";
import type { AppProps } from "next/app";
import { createBrowserSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { Session, SessionContextProvider } from "@supabase/auth-helpers-react";
import { useState } from "react";
import Head from "next/head";
import Header from "@/components/Header/header";

export default function App({
  Component,
  pageProps: { ...pageProps },
}: AppProps<{ initialSession: Session }>) {
  let supabaseUrl = process.env.SUPABASE_URL;
  let supabaseKey = process.env.SUPABASE_TOKEN;
  const [supabase] = useState(() =>
    createBrowserSupabaseClient({ supabaseUrl, supabaseKey })
  );
  return (
    <SessionContextProvider
      supabaseClient={supabase}
      initialSession={pageProps.initialSession}
    > 
      <Head>
        <title>CESI Match - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_temp.png" />
      </Head>
      <Header />

      <Component {...pageProps} />
      <footer></footer>
    </SessionContextProvider>
  );
}
