#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo '\n🏗️👷 Checking commit message before committing ... '

npx --no -- commitlint --edit ${1} ||
(
  echo '\n❌⭕❌⭕ Lint Format Failed ❌⭕❌⭕
    This commit is not a conventional commit name. Check the above errors and retry.';
    false;
)
