on: [ push ]
jobs:
  deploy-development:
    runs-on: ubuntu-latest
    if: github.ref_name == 'development'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/Projet-Collaboratif-CDA22/web-next-js-app:latest