on:
  push:
    branches: [develop]

jobs:
  deploy-config:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Create ENV file
        run: |
          touch .env
          echo NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }} >> .env
          echo NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} >> .env
          echo NEXT_PUBLIC_MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }} >> .env
      - name: Create cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .env
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
  integration-test:
    runs-on: ubuntu-latest
    needs: deploy-config
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Tests
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .env
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        run: npm run e2e:headless
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: e2e-tests
          path: cypress/videos
      - name: Create-PR
        if: success()
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: develop
          target_branch: recette
          title: "Auto Merge Request"
          body: "**Automated pull request**"
          new_string: "** Automatic pull request**"
          allow_no_diff: true
