on:
  pull_request:
    types: [ closed ]

jobs:
  deploy-config:
    runs-on: ubuntu-latest
    needs:
      - integration-test
      - Create-PR
    permissions:
      contents: read
      packages: write
    steps:
      - name: Create ENV file
        uses: actions/checkout@v3
        run: |
          touch .env
          echo NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }} >> .env
          echo NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} >> .env
          echo NEXT_PUBLIC_MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }} >> .env
      - name: Create cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .env
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
  deploy-docker:
    runs-on: ubuntu-latest
    needs: deploy-config
    if: success()
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            .env
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: docker-up
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_EC2 }}
      - run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEV_USERNAME }}@${{ secrets.DEV_HOST }} '
          docker-compose -f docker-compose.development.yml up -d --build'